version: '2.0'

services:
  oai-provider-db:
    container_name: oai-db
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    ports:
      - "4811:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: oaiprovider

  qucosa-oai-provider:
    container_name: oai-provider
    build:
      context: .
      dockerfile: ./Dockerfile.app
    ports:
      - "4812:8080"
    networks:
      - default
    links:
      - oai-provider-db:db
    depends_on:
      - oai-provider-db
    environment:
      WAIT_HOSTS: db:5432