version: '2.0'

services:
  db:
    container_name: oai-db
    hostname: oai-db
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    ports:
      - "4811:5432"
    environment:
      POSTGRES_PASSWORD: oaiprov
      POSTGRES_USER: postgres
      POSTGRES_DB: oaiprovider

  app:
    container_name: oai-provider
    build:
      context: .
      dockerfile: ./Dockerfile.app
    ports:
      - "4812:8080"
    networks:
      - default
    depends_on:
      - db
    environment:
      WAIT_HOSTS: oai-db:5432
      PSQL_URL: jdbc:postgresql://172.17.0.1:4811/oaiprovider
#      PSQL_USER:
      PSQL_PASSWD: oaiprov
#      MIN_POOL_SIZE:
#      MAX_POOL_SIZE:
#      APP_URL: